services:
  - type: web
    name: auto-vote-bot-python
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - selenium_bot.py
        - requirements.txt
        - Dockerfile
