services:
  - type: web
    name: auto-vote-bot-python
    env: docker
    region: singapore
    plan: free
    buildCommand: docker build -t auto-vote-bot-python .
    startCommand: docker run auto-vote-bot-python
